language: objective-c
script: 
- xctool test -project CircularStatesView.xcodeproj -scheme CircularStatesViewTests -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO
# - set -o pipefail && xcodebuild test -project CircularStatesView.xcodeproj -scheme CircularStatesViewTests -sdk iphonesimulator9.3 | xcpretty
# - pod lib lint
